//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextMenuLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextMenuLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysTool.Properties.ContextMenuLabels", typeof(ContextMenuLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Management.
        /// </summary>
        internal static string ComputerManagement {
            get {
                return ResourceManager.GetString("ComputerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PsExec Interative Session.
        /// </summary>
        internal static string PsExec {
            get {
                return ResourceManager.GetString("PsExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Registry.
        /// </summary>
        internal static string Remote_Registry {
            get {
                return ResourceManager.GetString("Remote Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Assistance.
        /// </summary>
        internal static string RemoteAssistance {
            get {
                return ResourceManager.GetString("RemoteAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Viewer.
        /// </summary>
        internal static string RemoteControlViewer {
            get {
                return ResourceManager.GetString("RemoteControlViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        internal static string RemoteDesktop {
            get {
                return ResourceManager.GetString("RemoteDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Group Policy Editor.
        /// </summary>
        internal static string RemoteGroupPolicyEditor {
            get {
                return ResourceManager.GetString("RemoteGroupPolicyEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Logoff.
        /// </summary>
        internal static string RemoteLogoff {
            get {
                return ResourceManager.GetString("RemoteLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Restart.
        /// </summary>
        internal static string RemoteRestart {
            get {
                return ResourceManager.GetString("RemoteRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveNode {
            get {
                return ResourceManager.GetString("RemoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Description.
        /// </summary>
        internal static string SetDescription {
            get {
                return ResourceManager.GetString("SetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Location.
        /// </summary>
        internal static string SetLocation {
            get {
                return ResourceManager.GetString("SetLocation", resourceCulture);
            }
        }
    }
}
